### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by ncamp**
Added date and location for BAY-SICSS

### CODE REVIEW

**Comment by ncamp** [comment]
Hey @cbail, this check has been pending for a few days... did I do something wrong?

**Comment by cbail** [comment]
Hi nick- we are still figuring out who is going to approve pull requests sorry. It may be me but it may also be the developers (plus many people have been offline because of the holidays)

**Comment by cbail** [comment]
I'm also not sure you need to make pull requests, Nick- some of the other organizers seem to have merging priveleges already. I'll check yours but see if you can do it on your own before I merge this ok? I'm also still waiting for some checks that your edits have not passed yet for some reason.

**Comment by ncamp** [comment]
I don't think I have write access (tried to re-edit).

**Comment by cbail** [comment]
I just checked and it looks like you do will email you a screenshot

**Comment by cbail** [comment]
Thanks Luke- did you have to wait for the tests to pass?

**Comment by lukebaker** [comment]
> Thanks Luke- did you have to wait for the tests to pass?

No, I merged using my administrator privileges. I think the issue is that the branch for this pull request was from a separate repository and it needs to be from this one. Those who have been added as collaborators cannot push directly to master, but they can push to this repository to their own branches. Once their changes are complete, they should create a pull request from their branch that is in this repository. Once all the tests, pass they should be able to merge the pull request themselves.

**Pull request merged**
